version: '3.8'
services:
  database:
    image: postgres 
    restart: always
    environment:
      POSTGRES_DB: poster
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/db
    ports:
      - '5432:5432'
    volumes:
      - poster:/data/db
  cache:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - poster:/data/cache
  api:
    build: .
    ports: 
      - "4000:4000"
    environment:
      REDIS_URL: cache:6379
      DATABASE_URL: postgresql://postgres:postgres@database:5432/poster
    env_file:
      - .env
volumes:
  poster:
    external: true