version: '3.8'
services:
  database:
    image: postgres 
    restart: always
    environment:
      POSTGRES_DB: poster
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/db
    ports:
      - '5432:5432'
    volumes:
      - poster:/data/db
  cache:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - poster:/data/cache
  api:
    build: .
    image: hitchcliff/poster
    ports: 
      - "4000:4000"
    environment:
      REDIS_URL: cache:6379
      # RDS_POSTGRES_URL: poster-db.cqqp651p6ntg.ap-southeast-1.rds.amazonaws.com
      # RDS_POSTGRES_USER: notkev1n
      # RDS_POSTGRES_PASSWORD: postappbuiltbykevin
      NODE_ENV: production
      RDS_POSTGRES_URL: database
      RDS_POSTGRES_USER: postgres
      RDS_POSTGRES_PASSWORD: postgres
    env_file:
      - .env
volumes:
  poster:
    external: true