version: '3.8'
services:
  database:
    image: postgres 
    restart: always
    environment:
      DB_URL: postgres://postgres:postgres@db-poster-02.cqqp651p6ntg.ap-southeast-1.rds.amazonaws.com:5432/poster?sslmode=true
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
  cache:
    image: redis
    restart: always
    environment:
      REDIS_URL: redis://poster-redis.dvcl5k.clustercfg.apse1.cache.amazonaws.com:6379
    ports:
      - '6379:6379'
  api:
    build: .
    image: hitchcliff/poster:v1.1
    ports: 
      - "4000:4000"
    environment:
      REDIS_URL: redis://cache:6379
      DB_URL: postgres://postgres:postgres@db-poster-02.cqqp651p6ntg.ap-southeast-1.rds.amazonaws.com:5432/poster?sslmode=true
      NODE_ENV: production
    env_file:
      - .env
    depends_on:
      - cache
      - database